import dotenv from 'dotenv';

dotenv.config();

export default {
  WEBHOOK_VERIFY_TOKEN: process.env.WEBHOOK_VERIFY_TOKEN,
  API_TOKEN: process.env.API_TOKEN,
  BUSINESS_PHONE: process.env.BUSINESS_PHONE,
  API_VERSION: process.env.API_VERSION,
  PORT: process.env.PORT || 3000,
  BASE_URL: process.env.BASE_URL,
  CREDENTIALS_TYPE: process.env.CREDENTIALS_TYPE,
  CREDENTIALS_PROJECT_ID: process.env.CREDENTIALS_PROJECT_ID,
  CREDENTIALS_PRIVATE_KEY_ID: process.env.CREDENTIALS_PRIVATE_KEY_ID,
  CREDENTIALS_PRIVATE_KEY: process.env.CREDENTIALS_PRIVATE_KEY,
  CREDENTIALS_CLIENT_EMAIL: process.env.CREDENTIALS_CLIENT_EMAIL,
  CREDENTIALS_CLIENT_ID: process.env.CREDENTIALS_CLIENT_ID,
  CREDENTIALS_AUTH_URI: process.env.CREDENTIALS_AUTH_URI,
  CREDENTIALS_TOKEN_URI: process.env.CREDENTIALS_TOKEN_URI,
  CREDENTIALS_AUTH_PROVIDER_X509_CERT_URL: process.env.CREDENTIALS_AUTH_PROVIDER_X509_CERT_URL,
  CREDENTIALS_CLIENT_X509_CERT_URL: process.env.CREDENTIALS_CLIENT_X509_CERT_URL,
  CREDENTIALS_UNIVERSE_DOMAIN: process.env.CREDENTIALS_UNIVERSE_DOMAIN
};